create table if not exists public.class_schedule_rules (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  session_time time not null,
  created_at timestamptz not null default now()
);

comment on table public.class_schedule_rules is
  'Recurring schedule rules for a class. day_of_week: 0=Sunday, 1=Monday, ..., 6=Saturday. Multiple rules per class are allowed (e.g. two sessions on the same day at different times).';

comment on column public.class_schedule_rules.day_of_week is
  '0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday.';

comment on column public.class_schedule_rules.session_time is
  'Local Jamaica time (-05:00) for the session.';

create table if not exists public.class_sessions (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  scheduled_at timestamptz not null,
  period_start date not null,
  created_at timestamptz not null default now(),
  unique (class_id, scheduled_at)
);

comment on table public.class_sessions is
  'Individual session instances for a class. Generated by admin for a 28-day period.';

comment on column public.class_sessions.scheduled_at is
  'Session date and time stored as timestamptz. Always use Jamaica UTC-5 offset when constructing this value — never UTC boundaries.';

comment on column public.class_sessions.period_start is
  'The 28-day billing period this session belongs to. Matches classes.current_period_start.';

create table if not exists public.class_attendance (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.class_sessions(id) on delete cascade,
  member_id uuid references public.members(id) on delete cascade,
  guest_profile_id uuid references public.guest_profiles(id) on delete cascade,
  marked_by uuid references public.profiles(id) on delete set null,
  marked_at timestamptz,
  created_at timestamptz not null default now(),
  constraint class_attendance_registrant_check
    check (
      (member_id is not null and guest_profile_id is null)
      or (member_id is null and guest_profile_id is not null)
    ),
  constraint class_attendance_unique_member
    unique (session_id, member_id),
  constraint class_attendance_unique_guest
    unique (session_id, guest_profile_id)
);

comment on table public.class_attendance is
  'Attendance records per session. Rows are created when a registration is made mid-period or when sessions are generated. marked_by and marked_at are null until front desk marks attendance.';

comment on column public.class_attendance.marked_at is
  'Null means attendance has not been marked yet. Front desk sets this when marking present.';

alter table public.class_schedule_rules enable row level security;
alter table public.class_sessions enable row level security;
alter table public.class_attendance enable row level security;

drop policy if exists "admins can read class_schedule_rules" on public.class_schedule_rules;
drop policy if exists "admins can insert class_schedule_rules" on public.class_schedule_rules;
drop policy if exists "admins can update class_schedule_rules" on public.class_schedule_rules;
drop policy if exists "admins can delete class_schedule_rules" on public.class_schedule_rules;
drop policy if exists "staff can read class_schedule_rules" on public.class_schedule_rules;

create policy "admins can read class_schedule_rules"
on public.class_schedule_rules
for select
to authenticated
using (public.is_admin());

create policy "admins can insert class_schedule_rules"
on public.class_schedule_rules
for insert
to authenticated
with check (public.is_admin());

create policy "admins can update class_schedule_rules"
on public.class_schedule_rules
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admins can delete class_schedule_rules"
on public.class_schedule_rules
for delete
to authenticated
using (public.is_admin());

create policy "staff can read class_schedule_rules"
on public.class_schedule_rules
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
  )
  and not public.is_admin()
);

drop policy if exists "admins can read class_sessions" on public.class_sessions;
drop policy if exists "admins can insert class_sessions" on public.class_sessions;
drop policy if exists "admins can update class_sessions" on public.class_sessions;
drop policy if exists "admins can delete class_sessions" on public.class_sessions;
drop policy if exists "staff can read class_sessions" on public.class_sessions;
drop policy if exists "trainers can read class_sessions" on public.class_sessions;

create policy "admins can read class_sessions"
on public.class_sessions
for select
to authenticated
using (public.is_admin());

create policy "admins can insert class_sessions"
on public.class_sessions
for insert
to authenticated
with check (public.is_admin());

create policy "admins can update class_sessions"
on public.class_sessions
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admins can delete class_sessions"
on public.class_sessions
for delete
to authenticated
using (public.is_admin());

create policy "staff can read class_sessions"
on public.class_sessions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
  )
  and not public.is_admin()
);

create policy "trainers can read class_sessions"
on public.class_sessions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
  )
  and not public.is_admin()
);

drop policy if exists "admins can read class_attendance" on public.class_attendance;
drop policy if exists "admins can insert class_attendance" on public.class_attendance;
drop policy if exists "admins can update class_attendance" on public.class_attendance;
drop policy if exists "admins can delete class_attendance" on public.class_attendance;
drop policy if exists "staff can read class_attendance" on public.class_attendance;
drop policy if exists "staff can insert class_attendance" on public.class_attendance;
drop policy if exists "staff can update class_attendance" on public.class_attendance;
drop policy if exists "trainers can read class_attendance" on public.class_attendance;

create policy "admins can read class_attendance"
on public.class_attendance
for select
to authenticated
using (public.is_admin());

create policy "admins can insert class_attendance"
on public.class_attendance
for insert
to authenticated
with check (public.is_admin());

create policy "admins can update class_attendance"
on public.class_attendance
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "admins can delete class_attendance"
on public.class_attendance
for delete
to authenticated
using (public.is_admin());

create policy "staff can read class_attendance"
on public.class_attendance
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and not ('Trainer' = any(coalesce(titles, '{}'::text[])))
  )
  and not public.is_admin()
);

create policy "staff can insert class_attendance"
on public.class_attendance
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and not ('Trainer' = any(coalesce(titles, '{}'::text[])))
  )
  and not public.is_admin()
);

create policy "staff can update class_attendance"
on public.class_attendance
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and not ('Trainer' = any(coalesce(titles, '{}'::text[])))
  )
  and not public.is_admin()
)
with check (
  exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and not ('Trainer' = any(coalesce(titles, '{}'::text[])))
  )
  and not public.is_admin()
);

create policy "trainers can read class_attendance"
on public.class_attendance
for select
to authenticated
using (
  exists (
    select 1
    from public.class_sessions class_session
    join public.class_trainers class_trainer
      on class_trainer.class_id = class_session.class_id
    join public.profiles profile
      on profile.id = auth.uid()
    where class_session.id = session_id
      and class_trainer.profile_id = auth.uid()
      and 'Trainer' = any(coalesce(profile.titles, '{}'::text[]))
  )
  and not public.is_admin()
);
